name: Run Gradle
description: Sets up Gradle JDKs and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
  java:
    required: true
    description: The JDK version
  token:
    required: false
    description: 'A Github PAT'
runs:
  using: composite
  steps:
    - name: Prepare OpenJDK
      shell: bash
      run: echo "JAVA_VERSION=${{ inputs.java }}" >> $GITHUB_ENV
    - name: Set up JDK ${{ inputs.java }}
      id: setup-jdk
      uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4.3.0
      with:
        java-version: ${{ inputs.java }}
        distribution: temurin
    - name: Setup Gradle
      id: setup-gradle
      uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
    - name: Run ${{ inputs.arguments }}
      shell: bash
      run: ./gradlew ${{ inputs.arguments }}